language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
notifications:
  email: false
before_install:
  - git config --global user.email "admin@ecocitycraft.com"
  - git config --global user.name "EcoCityCraft"
  - ./applyPatches.sh

# Added comment - 
